apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-webserver-kubernetes-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-webserver-kubernetes
  template:
    metadata:
      labels:
        app: go-webserver-kubernetes
    spec:
      containers:
        - name: go-webserver-kubernetes
          image: pablo152/go-webserver-kubernetes
